### PR TITLE
Fixes #5 – Add PusherModule.forRootAsync()

### LINKED ISSUE #5: Feature request: Add PusherModule.forRootAsync() to allow passing the options asynchronously
In addition to the current `forRoot()` method, a `forRootAsync()` option will make it easy to provide pusher options asynchronously. This option is specially useful if you rely on @NestJs' ConfgService to read environment variables from a `.env` file.

P.S: Send a PR shortly.

### PR DESCRIPTION
**Pull request by gulsharan**
- Added <kbd>forRootAsync()</kbd> method to PusherModule that expects a lambda that returns either <kbd>NextJsPusherOptions</kbd> or <kbd>Promise&lt;NextJsPusherOptions&gt;</kbd>
- Created a new interface <kbd>NextJsPusherOptions</kbd> for strong typing the new method
- Added unit tests for PusherModule

### CODE REVIEW

**Comment by underfisk** [comment]
@gulsharan This is a great addition, thank you!

**Comment by underfisk** [comment]
Check the v0.0.9, I have released including this PR

**Comment by gulsharan** [comment]
Works like magic! :)

**Comment by underfisk** [comment]
> Works like magic! :)

I'm glad to hear!

**Pull request merged**
